# Generated by Django 4.2.5 on 2023-10-27 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_food_tour'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
    ]
