# Generated by Django 4.2.5 on 2023-10-13 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_special'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='tour',
        ),
    ]
